# Generated by Django 5.1.1 on 2024-12-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('phone', 'phone'), ('laptop', 'laptop'), ('accessories', 'accessories')], max_length=100, null=True),
        ),
    ]
